### ISSUE TITLE
Proposed Features

### ISSUE THREAD

**Issue by Harshalzzzzzzz** [Artists-Forum-NITK/AF_Website#3]
Youtube or instagram APIs for adding them on website via dashboard
- https://www.toptal.com/django/youtube-api-integration-uploading-videos
- https://pypi.org/project/django-youtube-api/
- https://github.com/ivancrneto/youtube-django
- https://pypi.org/project/django-instagram/

3D models using <ModelViewer>

**Comment by SaurabhAgarwala** [comment]
Not required for current version as per the team discussion. Hence, closing
