### ISSUE TITLE
Master Branch Review

### ISSUE THREAD

**Issue by Harshalzzzzzzz** [Artists-Forum-NITK/AF_Website#7]
Review needed for master branch to fix code layout/style and improvements

**Comment by PiyushPI07** [comment]
I had some suggestions on the current frontend:
1. There's a lot of redundant code being used repeatedly on every page like Navbar, Header, and Footer. We have to make the as separate templates and use that template where required. 
2. The links in the navbar should perform a URL check. I mean if we are currently on Home, the Home link should be shown active on navbar and age should not reload upon clicking home button.

**Comment by Harshalzzzzzzz** [comment]
@PiyushPI07 I was also thinking about adding most of the static loaded files and sections within partials and sections .

**Comment by SaurabhAgarwala** [comment]
Resolved, hence closing
